<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PeekabooWin</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PeekabooWin.Core\PeekabooWin.Core.csproj" />
  </ItemGroup>
</Project>
